services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meetime-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - HUBSPOT_CLIENT_SECRET=${HUBSPOT_CLIENT_SECRET}
      - HUBSPOT_CLIENT_ID=${HUBSPOT_CLIENT_ID}
    networks:
      - meetime-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  meetime-network:
    driver: bridge